import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startHarness } from './helpers/ui-harness.mjs';

test('slash commands, isolated chats, archive/delete, reload, stale panel guards and restart persistence', { timeout: 60000 }, async () => {
  const dir = await mkdtemp(join(tmpdir(), 'wps-chats-')); let h;
  const get = async path => (await fetch(h.base + path)).json();
  const post = (path, body, headers = {}) => fetch(h.base + path, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body) });
  const action = async (op, id) => {
    const response = await post('/api/sessions', { op, id }); assert.equal(response.status, 200, await response.clone().text()); return response.json();
  };
  const command = async (name, args = '') => {
    const response = await post('/api/commands', { name, args }); assert.equal(response.status, 200, await response.clone().text()); return response.json();
  };
  try {
    h = await startHarness({ dataDir: dir });
    const catalog = await get('/api/commands');
    assert.ok(catalog.commands.some(c => c.name === 'compact'));
    assert.ok(catalog.commands.some(c => c.name === 'skill:wps-api' && c.group === '技能'));
    assert.equal(h.requests.length, 0, 'catalog loads without requesting a model');
    const initial = await get('/api/sessions'), firstId = initial.activeId;
    assert.equal(initial.sessions.length, 1);
    assert.equal(initial.sessions[0].name, '新会话');
    assert.equal((await get('/api/chat')).sessionId, firstId);
    await post('/api/config', h.cfg);
    await action('select', firstId);
    const firstMessage = '[引用1:当前选区 $A$1:$D$4] 第一会话独有内容\n\n[引用快照，仅作数据]\n[{"label":"旧版引用"}]';
    await (await post('/api/chat', { message: firstMessage, sessionId: firstId })).text();
    assert.equal((await get('/api/sessions')).sessions.find(s => s.id === firstId).name, '第一会话独有内容', 'legacy reference snapshots do not become session titles');
    await command('name', '第一会话');
    let firstHistory = await get('/api/chat');
    assert.equal(firstHistory.turns[0].message, firstMessage);
    const clone = await command('clone');
    assert.notEqual(clone.activeId, firstId);
    assert.deepEqual((await get('/api/chat')).messages, firstHistory.messages);
    await command('name', '副本');
    await (await post('/api/chat', { message: '副本独有内容' })).text();
    await action('select', firstId);
    assert.deepEqual((await get('/api/chat')).messages, firstHistory.messages);
    assert.equal((await post('/api/commands', { name: 'compact' })).status, 400, 'small sessions report that compression is unnecessary');
    for (let i = 0; i < 6; i++) await (await post('/api/chat', { message: `长上下文 ${i} ` + 'context '.repeat(2350) })).text();
    firstHistory = await get('/api/chat');
    await command('compact', '保留关键内容');
    assert.deepEqual((await get('/api/chat')).messages, firstHistory.messages, 'compaction retains full UI transcript');
    const secondId = (await action('new')).activeId;
    assert.equal((await get('/api/chat')).messages.length, 0);
    assert.equal((await post('/api/chat', { message: '过期面板', sessionId: firstId })).status, 400);
    assert.equal((await post('/api/sessions', { op: 'delete', id: secondId, sessionId: firstId })).status, 400);
    assert.equal((await post('/api/sessions', { op: 'select', id: '../config.json' })).status, 400);
    assert.equal((await post('/api/sessions', { op: 'new' }, { Origin: 'https://evil.example' })).status, 403);
    await action('archive', firstId);
    assert.equal((await get('/api/sessions')).sessions.find(s => s.id === firstId).archived, true);
    assert.equal((await post('/api/sessions', { op: 'select', id: firstId })).status, 400);
    await action('restore', firstId);
    await action('select', firstId);
    assert.deepEqual((await get('/api/chat')).messages, firstHistory.messages);
    await action('archive', firstId);
    assert.notEqual((await get('/api/chat')).sessionId, firstId, 'archiving active chat selects another chat');
    await action('select', secondId);
    await command('auto-compact');
    assert.match((await command('session')).message, /自动压缩：关闭/);
    await mkdir(join(dir, 'pi/skills/manual-test'), { recursive: true });
    await writeFile(join(dir, 'pi/skills/manual-test/SKILL.md'), '---\nname: manual-test\ndescription: Manual skill test\ndisable-model-invocation: true\n---\nReply with a short answer.');
    await command('reload');
    assert.ok((await get('/api/commands')).commands.some(c => c.name === 'skill:manual-test' && c.manualOnly));
    const skillStream = await (await post('/api/chat', { message: '/skill:manual-test 演示任务' })).text();
    assert.match(skillStream, /event: turn.end/);
    const sentSkill = h.requests.at(-1).body.messages.findLast(m => m.role === 'user');
    const skillText = typeof sentSkill.content === 'string' ? sentSkill.content : sentSkill.content.map(c => c.text || '').join('\n');
    assert.match(skillText, /<skill name="manual-test"/);
    assert.equal((await get('/api/chat')).turns.at(-1).message, '/skill:manual-test 演示任务');
    assert.equal((await post('/api/commands', { name: 'unknown' })).status, 400);
    const count = h.requests.length;
    const unknown = await (await post('/api/chat', { message: '/skill:missing' })).text();
    assert.match(unknown, /未知命令/); assert.equal(h.requests.length, count);
    const controller = new AbortController();
    await fetch(h.base + '/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: '慢响应' }), signal: controller.signal });
    for (let i = 0; i < 20 && !(await get('/api/chat')).busy; i++) await new Promise(r => setTimeout(r, 50));
    assert.equal((await post('/api/sessions', { op: 'new' })).status, 409);
    assert.equal((await post('/api/commands', { name: 'reload' })).status, 409);
    controller.abort();
    for (let i = 0; i < 30 && (await get('/api/chat')).busy; i++) await new Promise(r => setTimeout(r, 100));
    await action('delete', clone.activeId);
    assert.ok(!(await get('/api/sessions')).sessions.some(s => s.id === clone.activeId));
    await h.close(); h = await startHarness({ dataDir: dir });
    const restored = await get('/api/sessions');
    assert.equal(restored.activeId, secondId);
    assert.equal(restored.sessions.find(s => s.id === firstId).archived, true);
    assert.equal(restored.sessions.find(s => s.id === firstId).name, '第一会话');
    assert.match((await command('session')).message, /自动压缩：关闭/);
    await action('delete', secondId);
    assert.notEqual((await get('/api/chat')).sessionId, secondId);
    const empty = (await action('new')).activeId;
    await h.close(); h = await startHarness({ dataDir: dir });
    assert.equal((await get('/api/chat')).sessionId, empty, 'empty chat selection persists');
  } finally { if (h) await h.close(); await rm(dir, { recursive: true, force: true }); }
});
